"""empty message

Revision ID: 244639be2487
Revises: a7fc55f91751
Create Date: 2023-02-13 17:04:00.923161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244639be2487'
down_revision = 'a7fc55f91751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geolocation_coordinates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geolocation_recorder_md5_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geolocation_coordinates', schema=None) as batch_op:
        batch_op.drop_column('geolocation_recorder_md5_code')

    # ### end Alembic commands ###
