"""empty message

Revision ID: a7fc55f91751
Revises: 
Create Date: 2023-02-13 17:02:42.037013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fc55f91751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocation_coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('altitude', sa.Double(), nullable=True),
    sa.Column('accuracy', sa.Double(), nullable=True),
    sa.Column('altitudeAccuracy', sa.Double(), nullable=True),
    sa.Column('heading', sa.Double(), nullable=True),
    sa.Column('meter_per_second', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geolocation_recorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('md5_code', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geolocation_recorder')
    op.drop_table('geolocation_coordinates')
    # ### end Alembic commands ###
